### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'output/testfile.exe'

### ISSUE THREAD

**Issue by Lalika96** [G1ft3dC0d3/MsfMania#8]
Hi I always get this error message

Traceback (most recent call last)
  File "/root/MsfMania/MsfMania.py", line 253, in <module>
    original_file_size = check_file_size()
  File "/root/MsfMania/MsfMania.py", line 186, in check_file_size
    fs = path.getsize(filename)
  File "/usr/lib/python3.9/genericpath.py", line 50, in getsize
    return os.stat(filename).st_size
FileNotFoundError: [Errno 2] No such file or directory: 'output/testfile.exe'

**Comment by lepotekil** [comment]
Give all info, command, screenshot, etc.
Sorry for the delay.
